before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    main: ./cmd/server
    ldflags:
      - -s -w -X main.Version={{.Version}}

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip

dockers:
  - image_templates:
      - ghcr.io/crdant/mbta-mcp-server:{{ .Version }}
      - ghcr.io/crdant/mbta-mcp-server:latest
    dockerfile: Dockerfile.goreleaser
    build_flag_templates:
      - --label=org.opencontainers.image.created={{.Date}}
      - --label=org.opencontainers.image.title={{.ProjectName}}
      - --label=org.opencontainers.image.revision={{.FullCommit}}
      - --label=org.opencontainers.image.version={{.Version}}

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

nix:
  - name: mbta-mcp-server
    repository:
      owner: crdant
      name: nixpkgs
    homepage: https://github.com/crdant/mbta-mcp-server
    description: "An MCP server that communicates with the MBTA API to provide Boston-area transit information"
    license: "MIT"
    install: |
      mkdir -p $out/bin
      cp mbta-mcp-server $out/bin/
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com
    commit_msg_template: "{{ .ProjectName }}: {{ .Tag }}"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - Merge pull request
      - Merge branch