[devshell]
name = "mbta-mcp-server"
motd = """
🚇 Welcome to MBTA MCP Server development environment!

Commands:
  - make build    -- build the application
  - make run      -- run the application
  - make test     -- run all tests
  - make lint     -- run linter

Environment setup is handled by Nix flake and direnv.
"""

[[packages]]
name = "go"
help = "Go programming language"

[[packages]]
name = "golangci-lint"
help = "Go linters runner"

[[packages]]
name = "goreleaser"
help = "Release automation tool for Go projects"

[[packages]]
name = "melange"
help = "Build APK packages from source"

[[packages]]
name = "apko"
help = "Build OCI images from APK packages"

[[packages]]
name = "crane"
help = "Tool for interacting with remote images and registries"

[[packages]]
name = "cosign"
help = "Container signing and verification"

[[packages]]
name = "semver-cli"
category = "version management"
help = "Semantic versioning CLI tool from maykonlsf/semver-cli"

[[packages]]
name = "qemu_full"
category = "virtualization"
help = "QEMU virtual machine emulator"

[[env]]
# Development environment variables
name = "ENVIRONMENT"
value = "development"
