FROM scratch

# Import ca-certificates for secure connections
COPY --from=alpine:latest /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/

# Copy binary from build stage
COPY mbta-mcp-server /

# Expose port
EXPOSE 8080

# Run the service
ENTRYPOINT ["/mbta-mcp-server"]