name: Build and Package
# This workflow uses Chainguard actions for container builds with melange and apko

on:
  push:
    branches: [ main ]
    tags:
      - 'v*'
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  packages: write
  id-token: write  # Required for keyless signing with Cosign
  security-events: write  # Required for uploading SARIF results to GitHub Security tab
  actions: read  # Required for SBOM attestation

env:
  # Enable verbose debug output for GitHub Actions
  ACTIONS_RUNNER_DEBUG: true
  ACTIONS_STEP_DEBUG: true
  # Enable debug mode for apko and melange
  APKO_VERBOSITY: 3  # Maximum debug verbosity
  MELANGE_VERBOSITY: 3  # Maximum debug verbosity

jobs:
  build:
    name: Build, Test, and Package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          cache: true

      - name: Install semver CLI
        run: go install github.com/maykonlsf/semver-cli/cmd/semver@latest

      - name: Add Go bin directory to PATH
        run: echo "$(go env GOPATH)/bin" >> $GITHUB_PATH

      - name: Set version
        id: version
        run: |
          GIT_SHORT_SHA=$(git rev-parse --short HEAD)

          # Initialize semver if not already initialized
          if [[ ! -f .semver.yaml ]]; then
            semver init
          fi

          # Get the base version from semver
          BASE_VERSION=$(semver get release 2>/dev/null || echo "0.1.0")

          if [[ "${{ github.ref }}" == refs/tags/v* ]]; then
            VERSION="${{ github.ref_name }}"
            VERSION=${VERSION#v} # Remove v prefix
          elif [[ "${{ github.ref }}" == refs/heads/main ]]; then
            VERSION="$BASE_VERSION+build.$GIT_SHORT_SHA"
          else
            VERSION="$BASE_VERSION+build.$GIT_SHORT_SHA"
          fi

          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=sha,format=long
            type=ref,event=branch
            type=ref,event=tag,pattern={{version}}
            type=ref,event=pr
            type=raw,value=${{ steps.version.outputs.version }}

      - name: Install golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          args: --timeout=5m
          install-mode: binary

      - name: Format Check
        run: |
          go fmt ./...
          if [ -n "$(git status --porcelain)" ]; then
            echo "Code is not formatted. Please run 'go fmt ./...'"
            exit 1
          fi

      - name: Lint
        run: golangci-lint run

      - name: Vet
        run: go vet ./...

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...

      - name: Upload coverage report
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage.txt
          fail_ci_if_error: false

      - name: Install cosign
        uses: sigstore/cosign-installer@v3.1.1

      # Note: We use Chainguard actions for melange and apko builds
      # These actions internally handle tool installation

      - name: Install crane
        run: |
          # Install crane (no Chainguard action exists for this)
          CRANE_VERSION=$(curl -s https://api.github.com/repos/google/go-containerregistry/releases/latest | grep -Po '"tag_name": "v\K[^"]*')
          curl -L -o crane.tar.gz https://github.com/google/go-containerregistry/releases/download/v${CRANE_VERSION}/go-containerregistry_Linux_x86_64.tar.gz
          tar -xzf crane.tar.gz crane
          chmod +x crane
          sudo mv crane /usr/local/bin/

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Install ko
        run: |
          # Install ko
          echo "Installing ko..."
          go install github.com/google/ko@latest
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH

      - name: Build and push with ko
        id: ko_build
        run: |
          # Set up ko environment
          export KO_DOCKER_REPO=ghcr.io/${{ github.repository }}
          export VERSION=${{ steps.version.outputs.version }}

          # Build the image with ko and output to a local tar file for scanning
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            # For pull requests, just build locally but don't push
            echo "Building image locally for PR..."
            ko build --sbom=spdx --bare --local --platform=linux/amd64,linux/arm64 ./cmd/server -t $VERSION
            ko save --sbom=spdx --bare --platform=linux/amd64,linux/arm64 ./cmd/server -t $VERSION --oci-layout-path ./image-layout
          else
            # For main branch and tags, build and push
            echo "Building and pushing image..."
            ko build --sbom=spdx --bare --platform=linux/amd64,linux/arm64 ./cmd/server -t $VERSION
            # Save SBOM for use in later steps
            ko save --sbom=spdx --bare --platform=linux/amd64,linux/arm64 ./cmd/server -t $VERSION --oci-layout-path ./image-layout
          fi

          # Export the SBOM for later use
          cp ./image-layout/sbom-*.json ghcr.io/${{ github.repository }}.json

      - name: Tag additional versions
        if: github.event_name != 'pull_request'
        run: |
          # Ko already pushed the image with the VERSION tag
          # We just need to add additional tags if needed

          # Get the image reference that ko just pushed
          KO_IMAGE_REF="ghcr.io/${{ github.repository }}:${{ steps.version.outputs.version }}"
          IMAGE_DIGEST=$(crane digest ${KO_IMAGE_REF})

          # Create tags from metadata action output
          readarray -t DOCKER_TAGS <<< "${{ steps.meta.outputs.tags }}"

          # Tag with additional tags (skipping the first one which is already handled by ko)
          for TAG in "${DOCKER_TAGS[@]:1}"; do
            if [[ "${TAG}" != "${KO_IMAGE_REF}" ]]; then
              crane copy ${KO_IMAGE_REF} ${TAG}
              echo "Tagged with ${TAG}"
            fi
          done

          # Explicitly tag as latest if on main branch
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            crane tag ${KO_IMAGE_REF} ghcr.io/${{ github.repository }}:latest
            echo "Tagged as latest"
          fi

      - name: Sign image digest with keyless signing
        if: github.event_name != 'pull_request'
        env:
          COSIGN_EXPERIMENTAL: "true"
        run: |
          # Get the image reference that ko pushed
          KO_IMAGE_REF="ghcr.io/${{ github.repository }}:${{ steps.version.outputs.version }}"

          # Get the image digest (immutable content hash)
          IMAGE_DIGEST=$(crane digest ${KO_IMAGE_REF})
          echo "Image digest: ${IMAGE_DIGEST}"

          # Sign the image by digest only (immutable reference)
          IMAGE_REF="ghcr.io/${{ github.repository }}@${IMAGE_DIGEST}"
          echo "Signing image by digest: ${IMAGE_REF}"
          cosign sign "${IMAGE_REF}"

          # Add attestation to the digest reference
          cosign attest --predicate <(cat ghcr.io/${{ github.repository }}.json) "${IMAGE_REF}"

      - name: Verify image signature
        if: github.event_name != 'pull_request'
        env:
          COSIGN_EXPERIMENTAL: "true"
        run: |
          # Get the image reference that ko pushed
          KO_IMAGE_REF="ghcr.io/${{ github.repository }}:${{ steps.version.outputs.version }}"

          # Get the image digest (immutable content hash)
          IMAGE_DIGEST=$(crane digest ${KO_IMAGE_REF})

          # Verify only the digest-based signature
          IMAGE_REF="ghcr.io/${{ github.repository }}@${IMAGE_DIGEST}"
          echo "Verifying digest signature: ${IMAGE_REF}"
          cosign verify \
            --certificate-identity "https://github.com/${{ github.repository }}/.github/workflows/build.yml@${{ github.ref }}" \
            --certificate-oidc-issuer "https://token.actions.githubusercontent.com" \
            "${IMAGE_REF}"

          # Verify the SBOM attestation
          echo "Verifying SBOM attestation for: ${IMAGE_REF}"
          cosign verify-attestation \
            --certificate-identity "https://github.com/${{ github.repository }}/.github/workflows/build.yml@${{ github.ref }}" \
            --certificate-oidc-issuer "https://token.actions.githubusercontent.com" \
            --type spdx \
            "${IMAGE_REF}"

      - name: Scan image for vulnerabilities with Trivy
        if: github.event_name != 'pull_request'
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: "ghcr.io/${{ github.repository }}:${{ steps.version.outputs.version }}"
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH'
          ignore-unfixed: true

      - name: Upload Trivy scan results to GitHub Security tab
        if: github.event_name != 'pull_request'
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'trivy-results.sarif'
          category: 'trivy'

      - name: Upload SBOM
        if: github.event_name != 'pull_request'
        uses: actions/upload-artifact@v4
        with:
          name: sbom
          path: ghcr.io/${{ github.repository }}.json

      - name: Generate GitHub SBOM attestation
        if: github.event_name != 'pull_request'
        uses: actions/attest-sbom@v1
        with:
          subject-name: "mbta-mcp-server container image"
          subject-digest: "${{ steps.meta.outputs.digest }}"
          sbom-path: ghcr.io/${{ github.repository }}.json
          attestation-output: sbom-attestation.json

      - name: Upload SBOM attestation
        if: github.event_name != 'pull_request'
        uses: actions/upload-artifact@v4
        with:
          name: sbom-attestation
          path: sbom-attestation.json
