name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  packages: write
  id-token: write  # Required for keyless signing with Cosign

jobs:
  goreleaser:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          cache: true
      
      - name: Run Tests
        run: go test -v ./...
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COSIGN_EXPERIMENTAL: "1"  # Required for keyless signing
      
      - name: Install cosign
        uses: sigstore/cosign-installer@main

      - name: Verify signing
        run: |
          echo "Checking signing artifacts produced by GoReleaser:"
          ls -la dist/

          # Check for signature and certificate files
          if ls dist/*.sig >/dev/null 2>&1 && ls dist/*.pem >/dev/null 2>&1; then
            echo "✅ Signatures and certificates were generated successfully"
          else
            echo "⚠️ Signatures or certificates may be missing"
          fi

      - name: Upload assets
        uses: actions/upload-artifact@v4
        with:
          name: mbta-mcp-server
          path: dist/*